const Map<String, String> appStringsEn = {
  'appName': 'TripSplit',
  'appTagline': 'Split trip expenses offline',
  'splashLoading': 'Loading your trips...',
  'onboardingTitle1': 'Who paid what?',
  'onboardingDesc1': 'Track every expense on your trip — food, hotel, transport — all offline.',
  'onboardingTitle2': 'Who owes whom?',
  'onboardingDesc2': 'Instant settlement calculation. No internet needed at the beach.',
  'onboardingTitle3': 'Earn & customize',
  'onboardingDesc3': 'Collect coins daily, unlock themes, and premium features in the shop.',
  'getStarted': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',
  'navTrips': 'Trips',
  'navSettle': 'Settle',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'tripsTitle': 'My Trips',
  'tripsEmpty': 'No trips yet',
  'tripsEmptyDesc': 'Create your first trip and start splitting expenses with friends.',
  'createTrip': 'New Trip',
  'tripName': 'Trip name',
  'tripNameHint': 'e.g. Da Nang 2026',
  'members': 'Members',
  'memberNameHint': 'Member name',
  'addMember': 'Add member',
  'currency': 'Currency',
  'tripNote': 'Note (optional)',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'confirmDelete': 'Delete this trip?',
  'confirmDeleteDesc': 'All expenses will be permanently removed.',
  'tripLimitReached': 'Trip limit reached',
  'tripLimitDesc': 'Free plan allows {limit} trips. Unlock unlimited in the shop.',
  'goToShop': 'Go to Shop',
  'expenses': 'Expenses',
  'addExpense': 'Add Expense',
  'expenseTitle': 'Title',
  'expenseTitleHint': 'e.g. Seafood dinner',
  'amount': 'Amount',
  'paidBy': 'Paid by',
  'splitAmong': 'Split among',
  'selectAll': 'Select all',
  'category': 'Category',
  'note': 'Note',
  'noteHint': 'Add a note...',
  'date': 'Date',
  'totalSpent': 'Total spent',
  'noExpenses': 'No expenses yet',
  'noExpensesDesc': 'Add the first expense to start tracking.',
  'settlement': 'Settlement',
  'settlementTitle': 'Who owes whom',
  'everyoneSettled': 'Everyone is settled!',
  'everyoneSettledDesc': 'No payments needed. Great teamwork!',
  'owes': 'owes',
  'to': 'to',
  'balance': 'Balance',
  'shouldReceive': 'Should receive',
  'shouldPay': 'Should pay',
  'shareSettlement': 'Share result',
  'shareLocked': 'Unlock sharing in the shop',
  'exportTrip': 'Export trip',
  'exportLocked': 'Unlock export in the shop',
  'exportSuccess': 'Trip data copied',
  'customSplitLocked': 'Unlock custom % split in the shop',
  'customSplit': 'Custom split %',
  'multiCurrencyLocked': 'Unlock multi-currency in the shop',
  'expenseNoteLocked': 'Unlock expense notes in the shop',
  'settlementReward': '+{count} coins for checking settlement!',
  'catFood': 'Food',
  'catTransport': 'Transport',
  'catHotel': 'Hotel',
  'catShopping': 'Shopping',
  'catEntertainment': 'Fun',
  'catOther': 'Other',
  'shopTitle': 'Shop',
  'shopBrowse': 'Browse items',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Cards',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'yourWallet': 'Your wallet',
  'coinsLabel': 'coins',
  'earnCoins': 'Earn coins free',
  'earnCoinsDesc': 'Daily login + check settlements to earn coins.',
  'earnStepDaily': '• Daily login: +10 coins',
  'earnStepSettlement': '• Check settlement: +8 coins (max 3/day)',
  'earnStepBuy': '• Buy coin packs via Google Play',
  'claimDailyButton': 'Claim daily +10',
  'dailyRewardDone': 'Daily reward claimed',
  'buyCoins': 'Buy coins',
  'buyCoinsDesc': 'Purchase coin packs to unlock shop items faster.',
  'yourCoins': 'You have {count} coins',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} coins',
  'earnCoinsHint': 'Or earn coins for free in the wallet section above.',
  'billingDisabled': 'Google Billing is temporarily disabled',
  'billingUnavailable': 'Google Play Billing is not available',
  'productsNotFound': 'Products not found. Check Play Console setup.',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'configNetworkError': 'Network error. Using cached config.',
  'configTimeout': 'Request timed out. Using cached config.',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough coins',
  'alreadyOwned': 'Already owned',
  'owned': 'Owned',
  'active': 'Active',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Reset default',
  'resetToDefault': 'Reset to default',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide banner ads permanently.',
  'shopThemeSunset': 'Sunset theme',
  'shopThemeSunsetDesc': 'Warm coral & orange tones.',
  'shopThemeMidnight': 'Midnight theme',
  'shopThemeMidnightDesc': 'Cool blue night vibes.',
  'shopThemeTropical': 'Tropical theme',
  'shopThemeTropicalDesc': 'Fresh green island mood.',
  'shopThemeSakura': 'Sakura theme',
  'shopThemeSakuraDesc': 'Soft pink cherry blossom.',
  'shopBgTicket': 'Ticket card',
  'shopBgTicketDesc': 'Purple-to-coral ticket gradient.',
  'shopBgOcean': 'Ocean card',
  'shopBgOceanDesc': 'Blue wave gradient for trip cards.',
  'shopBgMountain': 'Mountain card',
  'shopBgMountainDesc': 'Misty mountain gradient.',
  'shopFeatUnlimited': 'Unlimited trips',
  'shopFeatUnlimitedDesc': 'Create unlimited trips (free: 3).',
  'shopFeatExport': 'Export & backup',
  'shopFeatExportDesc': 'Export trip data as JSON.',
  'shopFeatShare': 'Share settlement',
  'shopFeatShareDesc': 'Share who owes whom via any app.',
  'shopFeatCustomSplit': 'Custom % split',
  'shopFeatCustomSplitDesc': 'Split expenses by custom percentages.',
  'shopFeatMultiCurrency': 'Multi-currency',
  'shopFeatMultiCurrencyDesc': 'Use USD, EUR, VND and more.',
  'shopFeatExpenseNote': 'Expense notes',
  'shopFeatExpenseNoteDesc': 'Add notes to each expense.',
  'coinsAdded': 'Coins added to wallet!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'settlementRewardEarned': 'Settlement check reward!',
  'settingsTitle': 'Settings',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Vietnamese',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'version': 'Version',
  'about': 'About',
  'aboutDesc': 'TripSplit helps friend groups split trip expenses offline. No account needed.',
  'importData': 'Import backup',
  'importSuccess': 'Data imported successfully',
  'importFailed': 'Invalid backup data',
  'activeTheme': 'Active theme',
  'activeBackground': 'Active card style',
  'membersCount': '{count} members',
  'expensesCount': '{count} expenses',
  'minMembers': 'Need at least 2 members',
  'enterTripName': 'Enter trip name',
  'enterAmount': 'Enter amount',
  'selectPayer': 'Select who paid',
  'selectSplit': 'Select who to split among',
  'percentTotal': 'Total must equal 100%',
  'editTrip': 'Edit trip',
  'tripUpdated': 'Trip updated!',
  'cannotRemoveMember': 'Cannot remove — member has expenses',
  'currencyLockedHasExpenses': 'Cannot change currency while expenses exist',
  'adPlaceholder': 'Ad space',
  'adPlaceholderSub': 'Remove ads in the shop',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'TripSplit stores all trip data locally on your device. We do not collect personal information or upload your expense data to any server.\n\nInternet is used only to fetch IAP configuration (T106.json) and process Google Play purchases.\n\nPurchases are handled by Google Play Billing. We do not store payment card information.\n\nContact: support@tripsplit.app',
  'appearance': 'Appearance',
  'data': 'Data',
  'other': 'Other',
  'themeDark': 'Dark mode',
  'themeLight': 'Light mode',
  'exportBackup': 'Export all trips',
  'exportBackupLocked': 'Unlock in shop',
  'importBackup': 'Import backup',
  'openShop': 'Open shop',
  'openShopDesc': 'Buy themes, features & coins',
  'copyright': '© 2026 TripSplit',
  'activeCustomization': 'Customization',
};
