const Map<String, String> appStringsVi = {
  'appName': 'TripSplit',
  'appTagline': 'Chia tiền chuyến đi offline',
  'splashLoading': 'Đang tải chuyến đi...',
  'onboardingTitle1': 'Ai trả gì?',
  'onboardingDesc1': 'Ghi lại mọi khoản chi — ăn uống, khách sạn, xe — hoàn toàn offline.',
  'onboardingTitle2': 'Ai nợ ai?',
  'onboardingDesc2': 'Tính toán ngay tức thì. Không cần mạng khi đang đi chơi.',
  'onboardingTitle3': 'Cày điểm & tuỳ biến',
  'onboardingDesc3': 'Nhận coin mỗi ngày, mở khoá theme và tính năng premium trong shop.',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',
  'navTrips': 'Chuyến đi',
  'navSettle': 'Quyết toán',
  'navShop': 'Shop',
  'navSettings': 'Cài đặt',
  'tripsTitle': 'Chuyến đi',
  'tripsEmpty': 'Chưa có chuyến đi',
  'tripsEmptyDesc': 'Tạo chuyến đi đầu tiên và bắt đầu chia tiền với bạn bè.',
  'createTrip': 'Chuyến mới',
  'tripName': 'Tên chuyến đi',
  'tripNameHint': 'VD: Đà Nẵng 2026',
  'members': 'Thành viên',
  'memberNameHint': 'Tên thành viên',
  'addMember': 'Thêm thành viên',
  'currency': 'Tiền tệ',
  'tripNote': 'Ghi chú (tuỳ chọn)',
  'save': 'Lưu',
  'cancel': 'Huỷ',
  'delete': 'Xoá',
  'confirmDelete': 'Xoá chuyến đi này?',
  'confirmDeleteDesc': 'Tất cả khoản chi sẽ bị xoá vĩnh viễn.',
  'tripLimitReached': 'Đã đạt giới hạn',
  'tripLimitDesc': 'Miễn phí tối đa {limit} chuyến. Mở khoá không giới hạn tại shop.',
  'goToShop': 'Đến Shop',
  'expenses': 'Khoản chi',
  'addExpense': 'Thêm khoản chi',
  'expenseTitle': 'Tiêu đề',
  'expenseTitleHint': 'VD: Ăn hải sản',
  'amount': 'Số tiền',
  'paidBy': 'Ai trả',
  'splitAmong': 'Chia cho',
  'selectAll': 'Chọn tất cả',
  'category': 'Danh mục',
  'note': 'Ghi chú',
  'noteHint': 'Thêm ghi chú...',
  'date': 'Ngày',
  'totalSpent': 'Tổng chi',
  'noExpenses': 'Chưa có khoản chi',
  'noExpensesDesc': 'Thêm khoản chi đầu tiên để bắt đầu.',
  'settlement': 'Quyết toán',
  'settlementTitle': 'Ai nợ ai bao nhiêu',
  'everyoneSettled': 'Đã cân bằng hết!',
  'everyoneSettledDesc': 'Không cần chuyển tiền. Tuyệt vời!',
  'owes': 'nợ',
  'to': 'cho',
  'balance': 'Số dư',
  'shouldReceive': 'Được nhận',
  'shouldPay': 'Phải trả',
  'shareSettlement': 'Chia sẻ kết quả',
  'shareLocked': 'Mở khoá chia sẻ tại shop',
  'exportTrip': 'Xuất dữ liệu',
  'exportLocked': 'Mở khoá xuất dữ liệu tại shop',
  'exportSuccess': 'Đã sao chép dữ liệu',
  'customSplitLocked': 'Mở khoá chia % tuỳ chỉnh tại shop',
  'customSplit': 'Chia % tuỳ chỉnh',
  'multiCurrencyLocked': 'Mở khoá đa tiền tệ tại shop',
  'expenseNoteLocked': 'Mở khoá ghi chú tại shop',
  'settlementReward': '+{count} coin khi xem quyết toán!',
  'catFood': 'Ăn uống',
  'catTransport': 'Di chuyển',
  'catHotel': 'Khách sạn',
  'catShopping': 'Mua sắm',
  'catEntertainment': 'Vui chơi',
  'catOther': 'Khác',
  'shopTitle': 'Shop',
  'shopBrowse': 'Mua sắm',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Thẻ',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Không có item trong mục này',
  'yourWallet': 'Ví coin',
  'coinsLabel': 'coin',
  'earnCoins': 'Cày coin miễn phí',
  'earnCoinsDesc': 'Đăng nhập hàng ngày + xem quyết toán để nhận coin.',
  'earnStepDaily': '• Đăng nhập: +10 coin',
  'earnStepSettlement': '• Xem quyết toán: +8 coin (tối đa 3/ngày)',
  'earnStepBuy': '• Mua gói coin qua Google Play',
  'claimDailyButton': 'Nhận +10 hôm nay',
  'dailyRewardDone': 'Đã nhận thưởng hôm nay',
  'buyCoins': 'Mua coin',
  'buyCoinsDesc': 'Mua gói coin để mở khoá nhanh hơn.',
  'yourCoins': 'Bạn có {count} coin',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} coin',
  'earnCoinsHint': 'Hoặc cày coin miễn phí ở phần ví phía trên.',
  'billingDisabled': 'Google Billing tạm tắt',
  'billingUnavailable': 'Google Play Billing không khả dụng',
  'productsNotFound': 'Không tìm thấy sản phẩm. Kiểm tra Play Console.',
  'processingPurchase': 'Đang xử lý...',
  'openingBilling': 'Đang mở Google Play...',
  'configNetworkError': 'Lỗi mạng. Dùng cấu hình đã lưu.',
  'configTimeout': 'Hết thời gian chờ. Dùng cấu hình đã lưu.',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ coin',
  'alreadyOwned': 'Đã sở hữu',
  'owned': 'Đã mua',
  'active': 'Đang dùng',
  'apply': 'Áp dụng',
  'applied': 'Đã áp dụng!',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đã về mặc định',
  'shopRemoveAds': 'Bỏ quảng cáo',
  'shopRemoveAdsDesc': 'Ẩn banner quảng cáo vĩnh viễn.',
  'shopThemeSunset': 'Theme Hoàng hôn',
  'shopThemeSunsetDesc': 'Tông cam ấm áp.',
  'shopThemeMidnight': 'Theme Đêm',
  'shopThemeMidnightDesc': 'Xanh đêm mát mẻ.',
  'shopThemeTropical': 'Theme Nhiệt đới',
  'shopThemeTropicalDesc': 'Xanh lá đảo thông.',
  'shopThemeSakura': 'Theme Sakura',
  'shopThemeSakuraDesc': 'Hồng hoa anh đào.',
  'shopBgTicket': 'Thẻ vé',
  'shopBgTicketDesc': 'Gradient tím-cam kiểu vé.',
  'shopBgOcean': 'Thẻ biển',
  'shopBgOceanDesc': 'Gradient sóng xanh.',
  'shopBgMountain': 'Thẻ núi',
  'shopBgMountainDesc': 'Gradient núi sương mù.',
  'shopFeatUnlimited': 'Không giới hạn chuyến',
  'shopFeatUnlimitedDesc': 'Tạo không giới hạn (miễn phí: 3).',
  'shopFeatExport': 'Xuất & sao lưu',
  'shopFeatExportDesc': 'Xuất dữ liệu chuyến đi JSON.',
  'shopFeatShare': 'Chia sẻ quyết toán',
  'shopFeatShareDesc': 'Chia sẻ ai nợ ai qua app khác.',
  'shopFeatCustomSplit': 'Chia % tuỳ chỉnh',
  'shopFeatCustomSplitDesc': 'Chia khoản chi theo % riêng.',
  'shopFeatMultiCurrency': 'Đa tiền tệ',
  'shopFeatMultiCurrencyDesc': 'Dùng USD, EUR, VND...',
  'shopFeatExpenseNote': 'Ghi chú khoản chi',
  'shopFeatExpenseNoteDesc': 'Thêm ghi chú cho mỗi khoản.',
  'coinsAdded': 'Đã thêm coin vào ví!',
  'dailyRewardClaimed': 'Đã nhận thưởng hôm nay!',
  'settlementRewardEarned': 'Thưởng xem quyết toán!',
  'settingsTitle': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'english': 'English',
  'vietnamese': 'Tiếng Việt',
  'darkMode': 'Chế độ tối',
  'privacyPolicy': 'Chính sách bảo mật',
  'version': 'Phiên bản',
  'about': 'Giới thiệu',
  'aboutDesc': 'TripSplit giúp nhóm bạn chia tiền chuyến đi offline. Không cần tài khoản.',
  'importData': 'Nhập sao lưu',
  'importSuccess': 'Nhập dữ liệu thành công',
  'importFailed': 'Dữ liệu không hợp lệ',
  'activeTheme': 'Theme đang dùng',
  'activeBackground': 'Kiểu thẻ đang dùng',
  'membersCount': '{count} thành viên',
  'expensesCount': '{count} khoản chi',
  'minMembers': 'Cần ít nhất 2 thành viên',
  'enterTripName': 'Nhập tên chuyến đi',
  'enterAmount': 'Nhập số tiền',
  'selectPayer': 'Chọn người trả',
  'selectSplit': 'Chọn người chia',
  'percentTotal': 'Tổng phải bằng 100%',
  'adPlaceholder': 'Quảng cáo',
  'adPlaceholderSub': 'Bỏ quảng cáo tại shop',
  'privacyPolicyTitle': 'Chính sách bảo mật',
  'privacyPolicyBody': 'TripSplit lưu toàn bộ dữ liệu chuyến đi trên thiết bị. Chúng tôi không thu thập thông tin cá nhân hay tải dữ liệu chi tiêu lên server.\n\nInternet chỉ dùng để lấy cấu hình IAP (T106.json) và xử lý mua hàng Google Play.\n\nThanh toán qua Google Play Billing. Chúng tôi không lưu thông tin thẻ.\n\nLiên hệ: support@tripsplit.app',
  'appearance': 'Giao diện',
  'data': 'Dữ liệu',
  'other': 'Khác',
  'themeDark': 'Chế độ tối',
  'themeLight': 'Chế độ sáng',
  'exportBackup': 'Xuất tất cả chuyến',
  'exportBackupLocked': 'Mở khoá tại shop',
  'importBackup': 'Nhập sao lưu',
  'openShop': 'Mở shop',
  'openShopDesc': 'Mua theme, tính năng & coin',
  'copyright': '© 2026 TripSplit',
  'activeCustomization': 'Tuỳ biến',
};
